CREATE TABLE RM556364_PAIS(ID_PAIS NUMBER PRIMARY KEY,
                              NOME_PAIS VARCHAR(30)NOT NULL);
                              
CREATE TABLE RM556364_ESTADO (ID_ESTADO NUMBER PRIMARY KEY, 
                          NOME_ESTADO VARCHAR(30) NOT NULL,
                          ID_PAIS NUMBER);
                          
ALTER TABLE RM556364_ESTADO ADD CONSTRAINT FK_ESTADOEEEE FOREIGN KEY
(ID_PAIS) REFERENCES RM556364_PAIS(ID_PAIS);

SELECT * FROM RM556364_PAIS;

SELECT * FROM RM556364_ESTADO;

INSERT INTO RM556364_ESTADO VALUES (1, 'SÃO PAULO', 1);

INSERT INTO RM556364_PAIS VALUES (1, 'BRASIL');

                              
